//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EjercicioWebApi.Datos
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BibliotecaEntities : DbContext
    {
        public BibliotecaEntities()
            : base("name=BibliotecaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ComicBiblioteca> ComicBiblioteca { get; set; }
        public virtual DbSet<LibroBiblioteca> LibroBiblioteca { get; set; }
        public virtual DbSet<ObraCulturalBiblioteca> ObraCulturalBiblioteca { get; set; }
        public virtual DbSet<ObraDeVideoBiblioteca> ObraDeVideoBiblioteca { get; set; }
        public virtual DbSet<ObraLiterariaBiblioteca> ObraLiterariaBiblioteca { get; set; }
        public virtual DbSet<PeliculaBiblioteca> PeliculaBiblioteca { get; set; }
        public virtual DbSet<SerieTVBiblioteca> SerieTVBiblioteca { get; set; }
    }
}
