//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EjercicioWebApi.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class ComicBiblioteca
    {
        public long Id { get; set; }
        public long IdObra { get; set; }
        public string EditoraObra { get; set; }
        public long NumeroVolumenesObra { get; set; }
        public long CapitulosObra { get; set; }
    
        public virtual ObraLiterariaBiblioteca ObraLiterariaBiblioteca { get; set; }
    }
}
