//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EjercicioWebApi.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class ObraCulturalBiblioteca
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ObraCulturalBiblioteca()
        {
            this.ObraDeVideoBiblioteca = new HashSet<ObraDeVideoBiblioteca>();
            this.ObraLiterariaBiblioteca = new HashSet<ObraLiterariaBiblioteca>();
        }
    
        public long IdObra { get; set; }
        public string TituloObra { get; set; }
        public Nullable<long> AnyoObra { get; set; }
        public string GeneroObra { get; set; }
        public Nullable<bool> AlquiladoObra { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ObraDeVideoBiblioteca> ObraDeVideoBiblioteca { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ObraLiterariaBiblioteca> ObraLiterariaBiblioteca { get; set; }
    }
}
