//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EjercicioWebApi.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class ObraDeVideoBiblioteca
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ObraDeVideoBiblioteca()
        {
            this.PeliculaBiblioteca = new HashSet<PeliculaBiblioteca>();
            this.SerieTVBiblioteca = new HashSet<SerieTVBiblioteca>();
        }
    
        public long Id { get; set; }
        public long IdObra { get; set; }
        public string DirectorObra { get; set; }
        public string RepartoObra { get; set; }
    
        public virtual ObraCulturalBiblioteca ObraCulturalBiblioteca { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PeliculaBiblioteca> PeliculaBiblioteca { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SerieTVBiblioteca> SerieTVBiblioteca { get; set; }
    }
}
