//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EjercicioWebApi.Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class SerieTVBiblioteca
    {
        public long IdSerie { get; set; }
        public long IdObra { get; set; }
        public Nullable<long> TemporadasObra { get; set; }
        public Nullable<long> CapitulosObra { get; set; }
        public string CanalObra { get; set; }
    
        public virtual ObraDeVideoBiblioteca ObraDeVideoBiblioteca { get; set; }
    }
}
